version: "3.8"

services:
  api:
    build: .
    networks:
      - go-todo-network
    container_name: go-todo-api-container
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    command: go run main.go
    depends_on:
      - db
  db:
    image: postgres:14.2
    networks:
      - go-todo-network
    container_name: go-todo-db-container
    ports:
      - 4432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 1234
      TZ: "America/Sao_Paulo"

networks:
  go-todo-network:
    name: go-todo-network
    driver: bridge
